#!/usr/bin/env node
// mkwasmjs.js -- embed spf-min.wasm into spf-min-wasm.js (base64), so demo.html
// works straight from file:// (a classic <script src> loads fine from disk,
// while fetch() of a sibling .wasm is blocked by the browser's CORS rules).
// Re-run after rebuilding spf-min.wasm.
'use strict';
const fs = require('fs');
const path = require('path');
const src = path.join(__dirname, 'spf-min.wasm');
const dst = path.join(__dirname, 'spf-min-wasm.js');
const b64 = fs.readFileSync(src).toString('base64');
fs.writeFileSync(dst,
  '// generated by mkwasmjs.js from spf-min.wasm -- do not edit\n' +
  'window.SPF64_WASM_B64 = "' + b64 + '";\n');
console.log(dst + ': ' + b64.length + ' base64 chars');
