WINAPI: GetVersionExA KERNEL32.DLL

1 CONSTANT VER_PLATFORM_WIN32_WINDOWS
2 CONSTANT VER_PLATFORM_WIN32_NT

0 VALUE WinNT?

: InitWinNT ( -- )
  148 HERE !
  HERE GetVersionExA 0<>
  HERE 4 CELLS + @ VER_PLATFORM_WIN32_NT = AND TO WinNT?
; InitWinNT

..: AT-PROCESS-STARTING InitWinNT ;..
