\ $Id$
\ Конвертор IRC логов в HTML

REQUIRE STR@ ~ac/lib/str5.f
REQUIRE SPLIT ~pinka/samples/2005/lib/split.f
REQUIRE CONT ~profit/lib/bac4th.f
REQUIRE MAKE-IRC-MSG ~ygrek/lib/net/irc/basic.f
REQUIRE ENSURE ~ygrek/lib/debug/ensure.f
REQUIRE FileLines=> ~ygrek/lib/filelines.f
REQUIRE LAY-PATH ~pinka/samples/2005/lib/lay-path.f
REQUIRE TYPE>STR ~ygrek/lib/typestr.f
REQUIRE AsQName ~pinka/spf/quoted-word.f
REQUIRE OCCUPY ~pinka/samples/2005/lib/append-file.f
REQUIRE RAW-LOG-FILE ~ygrek/prog/web/irc/common.f

: put-header ( a u -- )
" <!DOCTYPE HTML PUBLIC {''}-//W3C//DTD HTML 4.0 Transitional//EN{''}>
<HTML>
<HEAD>
<META HTTP-EQUIV={''}Content-Type{''} CONTENT={''}text/html; charset=windows-1251{''}>
<META NAME={''}title{''} CONTENT={''}Log of #forth{''}>
<META NAME={''}Author{''} CONTENT={''}exsample{''}>
<META NAME={''}Keywords{''} CONTENT={''}logs, logging, channel, irc, bot, exsample, log2html{''}>
<META NAME={''}robots{''} CONTENT= {''}index,all{''}>
<style type={''}text/css{''}>
<!--
.time {S' {'}color: #AAAAAA; text-decoration: none;}
.else {S' {'}color: #009900; font-style: italic;}
.nick {S' {'}color: #0000AA;}
//-->
</style>
<TITLE>Log of #forth. {s}</TITLE>
</head>
<body>"
STYPE ;

: put-footer
" <hr/>
<span style={''}color:black; font-size: 0.8em;{''}>Generated by log2html for exsample</span>
</body>
</html>"
STYPE ;

0 VALUE time
0 VALUE msg

: put-time ( a u -- ) time STR@ 2DUP 2DUP " <a id={''}{s}{''} href={''}#{s}{''} class={''}time{''}>[{s}]</a>" STYPE ;
: put-nick ( a u -- ) " <font class={''}nick{''}>[{s}]</font>" STYPE ;
: put-text ( a u -- ) SPACE TYPE ;
: sput-text DUP STR@ TYPE STRFREE ;
: sput-else ( s -- ) DUP STR@ " <font class={''}else{''}> {s}</font>" STYPE STRFREE ;
: put-break ( -- ) S" <br/>" TYPE CR ;

: line=> PRO put-time CONT put-break ;

: put-message-text
   msg irc-msg-text irc-action?
   IF msg irc-msg-sender " <b>{s}</b> {s}" sput-text
   ELSE msg irc-msg-sender put-nick ( a u ) put-text
   THEN ;

MODULE: BOT-LOG-TALK

: PRIVMSG line=> put-message-text ;
: NICK line=> msg irc-msg-text msg irc-msg-sender " {s} changed nick to {s}" sput-else ;
: QUIT line=> msg irc-msg-text msg irc-msg-sender " {s} quit ({s})" sput-else ;
: PART line=> msg irc-msg-text msg irc-msg-target msg irc-msg-sender " {s} left {s} ({s})" sput-else ;
: JOIN line=> msg irc-msg-text msg irc-msg-sender " {s} joined {s}" sput-else ;

: NOTFOUND -1 THROW ;

: '' '' ;

;MODULE

: each-line ( a u -- )
   S" |" SPLIT- ENSURE " {s}" TO time
   MAKE-IRC-MSG 0= IF FREE-IRC-MSG EXIT THEN TO msg
   GET-ORDER
   ONLY BOT-LOG-TALK
   msg irc-msg-cmd ['] EVALUATE CATCH IF 2DROP THEN
   SET-ORDER
   msg FREE-IRC-MSG
;

: (log2html) { d m y -- }
   d m y RAW-LOG-FILE
   2DUP FILE-EXISTS NOT IF 2DROP EXIT THEN
   " {#d}/{#m}/{#y}" DUP STR@ put-header STRFREE
   START{ FileLines=> DUP STR@ each-line }EMERGE
   put-footer ;

: log2html { d m y | s -- }
   d m y ['] (log2html) TYPE>STR -> s
   s STRLEN 0 <> IF
     s STR@
     d m y HTML-LOG-FILE
     FORCE-PATH OCCUPY
   THEN
   s STRFREE ;

