REQUIRE SO  ~ac/lib/ns/so-xt.f
REQUIRE {   lib/ext/locals.f

\ db options
0x2    CONSTANT CL_DB_PHISHING	    
0x8    CONSTANT CL_DB_PHISHING_URLS 
0x10   CONSTANT CL_DB_PUA	    
0x20   CONSTANT CL_DB_CVDNOTMP	      \ obsolete
0x40   CONSTANT CL_DB_OFFICIAL	      \ internal
0x80   CONSTANT CL_DB_PUA_MODE	    
0x100  CONSTANT CL_DB_PUA_INCLUDE   
0x200  CONSTANT CL_DB_PUA_EXCLUDE   
0x400  CONSTANT CL_DB_COMPILED	      \ internal
0x800  CONSTANT CL_DB_DIRECTORY	      \ internal
0x1000 CONSTANT CL_DB_OFFICIAL_ONLY 
0x2000 CONSTANT CL_DB_BYTECODE      
0x4000 CONSTANT CL_DB_SIGNED	    

CL_DB_PHISHING CL_DB_PHISHING_URLS OR CL_DB_BYTECODE OR CONSTANT CL_DB_STDOPT


\ scan options
0x0     CONSTANT CL_SCAN_RAW			
0x1     CONSTANT CL_SCAN_ARCHIVE			
0x2     CONSTANT CL_SCAN_MAIL			
0x4     CONSTANT CL_SCAN_OLE2			
0x8     CONSTANT CL_SCAN_BLOCKENCRYPTED		
0x10    CONSTANT CL_SCAN_HTML			
0x20    CONSTANT CL_SCAN_PE			
0x40    CONSTANT CL_SCAN_BLOCKBROKEN		
0x80    CONSTANT CL_SCAN_MAILURL       \ ignored
0x100   CONSTANT CL_SCAN_BLOCKMAX      \ ignored
0x200   CONSTANT CL_SCAN_ALGORITHMIC		
0x800   CONSTANT CL_SCAN_PHISHING_BLOCKSSL \ ssl mismatches, not ssl by itself
0x1000  CONSTANT CL_SCAN_PHISHING_BLOCKCLOAK	
0x2000  CONSTANT CL_SCAN_ELF			
0x4000  CONSTANT CL_SCAN_PDF			
0x8000  CONSTANT CL_SCAN_STRUCTURED		
0x10000 CONSTANT CL_SCAN_STRUCTURED_SSN_NORMAL	
0x20000 CONSTANT CL_SCAN_STRUCTURED_SSN_STRIPPED	
0x40000 CONSTANT CL_SCAN_PARTIAL_MESSAGE         
0x80000 CONSTANT CL_SCAN_HEURISTIC_PRECEDENCE    

CL_SCAN_ARCHIVE CL_SCAN_MAIL OR CL_SCAN_OLE2 OR CL_SCAN_PDF OR
CL_SCAN_HTML OR CL_SCAN_PE OR CL_SCAN_ALGORITHMIC OR CL_SCAN_ELF OR
CONSTANT CL_SCAN_STDOPT

ALSO SO NEW: libclamav.dll
ALSO SO NEW: libclamav.so

: CL_ScanFile { fa fu eng \ scanned virname -- va vu flag }
  CL_SCAN_STDOPT eng ^ scanned ^ virname fa 5 cl_scanfile
  IF virname ASCIIZ> TRUE ELSE S" " FALSE THEN
;
