\ строка коментария
1 ERROR_INVALID_FUNCTION
2 ERROR_FILE_NOT_FOUND
3 ERROR_PATH_NOT_FOUND
4 ERROR_TOO_MANY_OPEN_FILES
5 ERROR_ACCESS_DENIED
6 ERROR_INVALID_HANDLE
7 ERROR_ARENA_TRASHED
8 ERROR_NOT_ENOUGH_MEMORY
9 ERROR_INVALID_BLOCK
10 ERROR_BAD_ENVIRONMENT
11 ERROR_BAD_FORMAT
12 ERROR_INVALID_ACCESS
13 ERROR_INVALID_DATA
14 ERROR_OUTOFMEMORY
15 ERROR_INVALID_DRIVE
15 ERROR_CURRENT_DIRECTORY
17 ERROR_NOT_SAME_DEVICE
18 ERROR_NO_MORE_FILES
19 ERROR_WRITE_PROTECT
20 ERROR_BAD_UNIT
21 ERROR_NOT_READY
22 ERROR_BAD_COMMAND
23 ERROR_CRC
24 ERROR_BAD_LENGTH
25 ERROR_SEEK
26 ERROR_NOT_DOS_DISK
27 ERROR_SECTOR_NOT_FOUND
28 ERROR_OUT_OF_PAPER
29 ERROR_WRITE_FAULT
30 ERROR_READ_FAULT
31 ERROR_GEN_FAILURE
32 ERROR_SHARING_VIOLATION
33 ERROR_LOCK_VIOLATION
34 ERROR_WRONG_DISK
36 ERROR_SHARING_BUFFER_EXCEEDED
38 ERROR_HANDLE_EOF
39 ERROR_HANDLE_DISK_FULL
50 ERROR_NOT_SUPPORTED
123 ERROR_INVALID_NAME
  1 Неверный номер функции
  2 Файл не найден\ ( =-38)
  3 Путь не найден
  4 Слишком много открытых файлов
  5 Доступ запрещен
  6 Неверный хэндл
  7 Уничтожены блоки управления памятью DOS
  8 Мало памяти DOS
  9 Неверный адрес блока памяти DOS
 -1 ABORT
 -2 ABORT"
 -3 Переполнение стека
 -4 Исчерпание стека
 -5 Переполнение стека возвратов
 -6 Исчерпание стека возвратов
 -7 Слишком глубокое вложение DO-LOOP во время выполнения
 -8 Переполнение словаря
 -9 Неверный адрес памяти
-10 Деление на ноль
-11 Результат вне диапазона
-12 Несоответствие типа аргумента
-13 Неопределенное слово
-14 Интерпретация слова, предназначенного только для компиляции
-15 Неверный FORGET
-16 Попытка использования строки нулевой длины как имени
-17 Переполнение строки форматного вывода
-18 Переполнение выделяемой строки
-19 Слишком длинное имя определения
-20 Запись в место только для чтения
-21 Неподдерживаемая операция
-22 Несоответствие управляющих структур
-23 Исключение выравнивания адресов
-24 Неверный числовой аргумент
-25 Сбой стека возвратов
-26 Недоступны параметры цикла
-27 Неверная рекурсия
-28 Прерывание пользователем
-29 Вложенная компиляция
-30 Устаревшая возможность
-31 >BODY используется для слова, определенного не через CREATE
-32 Неверное имя (например, TO xxx)
-33 Исключение чтения блока
-34 Исключение записи блока
-35 Неверный номер блока
-36 Неверная позиция в файле
-37 Исключение файлового ввода/вывода
-38 Несуществующий файл
-39 Неожидаемый конец файла
-40 Неверное BASE для преобразований с плавающей точкой
-41 Потеря точности
-42 Вещественное деление на ноль
-43 Результат с плавающей точкой вне диапазона
-44 Переполнение стека чисел с плавающей точкой
-45 Исчерпание стека чисел с плавающей точкой
-46 Неверный аргумент с плавающей точкой
-47 Удален список слов компиляции
-48 Неверный POSTPONE
-49 Переполнение цепочки поиска
-50 Исчерпание цепочки поиска
-51 Изменен список слов компиляции
-52 Переполнение управляющего стека
-53 Переполнение стека исключений
-54 Вещественное исчерпание
-55 Неопределенный вещественный сбой
-56 QUIT
-57 Исключение в передаче или приеме символа
-58 Исключение [IF], [ELSE] или [THEN]
-257 Ошибка записи - нет места на диске ?
-300 Мало памяти (allocate) !
-305 Ошибка открытия файла !
-306 Ошибка закрытия файла !
-307 Ошибка создания файла !
-308 Ошибка перемещения указателя ч/з !
-309 Не число !
-311 Исчерпание стека !
-312 Только для режима компиляции !
-314 Слишком далекий переход !
-315 Непарные операторы IF..ELSE !
-316 Непарные операторы IF..THEN !
-317 UNTIL без BEGIN !
-318 REPEAT без WHILE !
-319 REPEAT без BEGIN !
-320 AGAIN без BEGIN !
-321 - не найдено !
-322 Деление на 0 !
-330 Непарные скобки !\ -330-336 - сообщения ассемблера
-331 Требуется режим исполнения !
-332 Ошибка >NAME !
-333 Неверный операнд !
-334 Неразрешенная метка !
-335 Слишком много меток !
-336 Неверный регистр !
-337 Сбой стека по CSP !\ -337-339 - сообщения DIR.F
-338 Неверный каталог !
-339 Неверный диск !
-340 Ошибка распределения памяти !\ -340-345 - сообщения FE
-341 Ошибка чтения !
-342 Файл не найден !
-343 Помощь недоступна.
-344 Нет указанного файла !
-345 Не могу найти HLP-файл !
-346 Исчерпание памяти !\ сообщение SORT2.F
-347 Не хватает стека !\ сообщение SORT2.F
-350 Мало памяти (FE)!\ -350-354 - сообщения FE 2.5
-351 Неверный индекс блока (FE)!
-352 Неизвестный метод (FE)!
-353 Попытка послать сообщение несуществующему предку (FE)!
-354 Критическая ошибка распределения памяти (FE)!
-355 Переполнение IDX-сегмента (FE)!
-356 Не найдена переменная (класс csCheck) (FE)!
-357 Не найдена процедура меню (FE)!
-358 Не найдена процедура в команде KEY (FE)!
-359 Прерывание Ctrl+Break (FE)!
-360 Прервано по критической ошибке DOS!
-2001 -? (не literal)
-2002 -?? (не число)
-2003 WORD OR FILE NOT FOUND
-2004 UNTIL без BEGIN !
-2005 REPEAT без BEGIN !
-2006 AGAIN без BEGIN !
-2007 Conditionals not paired
-2009 Library not found
-2010 Procedure not found
-2011 Unknown vocabulary
0xC0000001 UNSUCCESSFUL
0x00000000 WAIT_0
0x00000080 ABANDONED_WAIT_0
0x000000C0 USER_APC
0x00000102 TIMEOUT
0x00000103 PENDING
0x80000001 GUARD_PAGE_VIOLATION
0x80000002 DATATYPE_MISALIGNMENT
0x80000003 BREAKPOINT
0x80000004 SINGLE_STEP
0xC0000005 ACCESS_VIOLATION
0xC0000006 IN_PAGE_ERROR
0xC000000D INVALID_PARAMETER
0xC0000017 NO_MEMORY
0xC000001C INVALID_SYSTEM_SERVICE
0xC000001D ILLEGAL_INSTRUCTION
0xC0000025 NONCONTINUABLE_EXCEPTION
0xC0000026 INVALID_DISPOSITION
0xC000008C ARRAY_BOUNDS_EXCEEDED
0xC000008D FLOAT_DENORMAL_OPERAND
0xC000008E FLOAT_DIVIDE_BY_ZERO
0xC000008F FLOAT_INEXACT_RESULT
0xC0000090 FLOAT_INVALID_OPERATION
0xC0000091 FLOAT_OVERFLOW
0xC0000092 FLOAT_STACK_CHECK
0xC0000093 FLOAT_UNDERFLOW
0xC0000094 INTEGER_DIVIDE_BY_ZERO
0xC0000095 INTEGER_OVERFLOW
0xC0000096 PRIVILEGED_INSTRUCTION
0xC00000FD STACK_OVERFLOW
0x80000113 USER_BREAK
0xC000013A CONTROL_C_EXIT
0xC00000AA INSTRUCTION_MISALIGNMENT
10000 WSABASEERR
10004 WSAEINTR
10009 WSAEBADF
10013 WSAEACCES
10014 WSAEFAULT
10022 WSAEINVAL
10024 WSAEMFILE
10035 WSAEWOULDBLOCK
10036 WSAEINPROGRESS
10037 WSAEALREADY
10038 WSAENOTSOCK
10039 WSAEDESTADDRREQ
10040 WSAEMSGSIZE
10041 WSAEPROTOTYPE
10042 WSAENOPROTOOPT
10043 WSAEPROTONOSUPPORT
10044 WSAESOCKTNOSUPPORT
10045 WSAEOPNOTSUPP
10046 WSAEPFNOSUPPORT
10047 WSAEAFNOSUPPORT
10048 WSAEADDRINUSE
10049 WSAEADDRNOTAVAIL
10050 WSAENETDOWN
10051 WSAENETUNREACH
10052 WSAENETRESET
10053 WSAECONNABORTED
10054 WSAECONNRESET
10055 WSAENOBUFS
10056 WSAEISCONN
10057 WSAENOTCONN
10058 WSAESHUTDOWN
10059 WSAETOOMANYREFS
10060 WSAETIMEDOUT
10061 WSAECONNREFUSED
10062 WSAELOOP
10063 WSAENAMETOOLONG
10064 WSAEHOSTDOWN
10065 WSAEHOSTUNREACH
10066 WSAENOTEMPTY
10067 WSAEPROCLIM
10068 WSAEUSERS
10069 WSAEDQUOT
10070 WSAESTALE
10071 WSAEREMOTE
10101 WSAEDISCON
10091 WSASYSNOTREADY
10092 WSAVERNOTSUPPORTED
10093 WSANOTINITIALISED
11001 WSAHOST_NOT_FOUND
11002 WSATRY_AGAIN
11003 WSANO_RECOVERY
11004 WSANO_DATA
0 Unknown error
