CONCEIVE 
`NodeName & EXEC, `var SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW `ALIGN & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, `HERE & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 0 LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-LIT & EXEC, `, & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, `CONCEIVE & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, `LIT, & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, `BIRTH & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, `name SLIT, 
`GetAttribute & EXEC, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-SLIT & EXEC, `NAMING- & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `rem SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `comment SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `g SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`trans-childs & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `forth SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`trans-childs & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `p SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW `CONCEIVE & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`trans-childs & EXEC, 
`STATE & EXEC, 
`1-! & EXEC, `BIRTH & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `def SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW `CONCEIVE & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`trans-childs & EXEC, 
`STATE & EXEC, 
`1-! & EXEC, `BIRTH & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, `name SLIT, 
`GetAttribute & EXEC, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-SLIT & EXEC, `NAMING- & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `lit SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`STATE & EXEC, 
`1-! & EXEC, 
`trans-childs & EXEC, `LIT, & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `slit SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`STATE & EXEC, 
`1-! & EXEC, 
`trans-childs & EXEC, `SLIT, & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `exec SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`STATE & EXEC, 
`1-! & EXEC, 
`trans-childs & EXEC, `EXEC, & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `exit SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`STATE & EXEC, 
`1-! & EXEC, `EXIT, & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `recurse SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`STATE & EXEC, 
`1-! & EXEC, `GERM & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, `EXEC, & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `again SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`STATE & EXEC, 
`1-! & EXEC, `GERM & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, `gtCS & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, `BBW, & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `otherwise SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`trans-childs & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `when SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`STATE & EXEC, 
`1-! & EXEC, `ZBFW, & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`trans-childs & EXEC, 
`STATE & EXEC, 
`1-! & EXEC, `BFW2, & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, `RFW & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `choose SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`trans-childs & EXEC, 
`cnode & EXEC, 
`gtR & EXEC, `when SLIT, 
`2gtR & EXEC, 
`2R@ & EXEC, 
`FirstChildByTagName & EXEC, MBW 
`cnode & EXEC, ZBFW2, 
`STATE & EXEC, 
`1-! & EXEC, `RFW & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`2R@ & EXEC, 
`NextSiblingByTagName & EXEC, BBW, RFW 
`RDROP & EXEC, 
`RDROP & EXEC, 
`Rgt & EXEC, 
`cnode! & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `while SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`STATE & EXEC, 
`1-! & EXEC, `ZBFW2, & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `repeat SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`STATE & EXEC, 
`1-! & EXEC, `MBW & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`trans-childs & EXEC, 
`STATE & EXEC, 
`1-! & EXEC, `BBW, & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`cnode & EXEC, 
`gtR & EXEC, `while SLIT, 
`2gtR & EXEC, 
`2R@ & EXEC, 
`FirstChildByTagName & EXEC, MBW 
`cnode & EXEC, ZBFW2, 
`STATE & EXEC, 
`1-! & EXEC, `RFW & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`2R@ & EXEC, 
`NextSiblingByTagName & EXEC, BBW, RFW 
`RDROP & EXEC, 
`RDROP & EXEC, 
`Rgt & EXEC, 
`cnode! & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `until SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`STATE & EXEC, 
`1-! & EXEC, `MBW & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`trans-childs & EXEC, 
`STATE & EXEC, 
`1-! & EXEC, `ZBBW, & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`cnode & EXEC, 
`gtR & EXEC, `while SLIT, 
`2gtR & EXEC, 
`2R@ & EXEC, 
`FirstChildByTagName & EXEC, MBW 
`cnode & EXEC, ZBFW2, 
`STATE & EXEC, 
`1-! & EXEC, `RFW & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`2R@ & EXEC, 
`NextSiblingByTagName & EXEC, BBW, RFW 
`RDROP & EXEC, 
`RDROP & EXEC, 
`Rgt & EXEC, 
`cnode! & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `if SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`STATE & EXEC, 
`1-! & EXEC, `ZBFW, & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`trans-childs & EXEC, 
`STATE & EXEC, 
`1-! & EXEC, `RFW & LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
`STATE & EXEC, 
`1+! & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`STATE & EXEC, 
`@ & EXEC, 0 LIT, 
`neq & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`NodeName & EXEC, `choose SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`trans-childs & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`STATE & EXEC, 
`@ & EXEC, 0 LIT, 
`neq & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`NodeName & EXEC, `otherwise SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`trans-childs & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`STATE & EXEC, 
`@ & EXEC, 0 LIT, 
`neq & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`NodeName & EXEC, `when SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW ZBFW, 
`trans-childs & EXEC, 
`ParentNode & EXEC, 
`LastChild & EXEC, RFW 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`STATE & EXEC, 
`@ & EXEC, 0 LIT, 
`neq & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`NodeName & EXEC, `if SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW ZBFW, 
`trans-childs & EXEC, RFW 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`STATE & EXEC, 
`@ & EXEC, 0 LIT, 
`neq & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`NodeName & EXEC, `repeat SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`FALSE & EXEC, 
`gtCS & EXEC, MBW 
`trans-childs & EXEC, 
`CS@ & EXEC, ZBBW, 
`CSDROP & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`STATE & EXEC, 
`@ & EXEC, 0 LIT, 
`neq & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`NodeName & EXEC, `while SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`0= & EXEC, ZBFW, 
`ParentNode & EXEC, 
`LastChild & EXEC, 
`CSDROP & EXEC, 
`TRUE & EXEC, 
`gtCS & EXEC, RFW 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`STATE & EXEC, 
`@ & EXEC, 0 LIT, 
`neq & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`NodeName & EXEC, `until SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`FALSE & EXEC, 
`gtCS & EXEC, MBW 
`trans-childs & EXEC, 
`CS@ & EXEC, 
`OR & EXEC, ZBBW, 
`CSDROP & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `#comment SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`TRUE & EXEC, BIRTH advice-trule-before CONCEIVE 
`NodeName & EXEC, `#text SLIT, 
`CEQUAL & EXEC, 
`0= & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`NodeValue & EXEC, 
`T-TEXT & EXEC, 
`TRUE & EXEC, BIRTH advice-trule-before 