\ $Id$

REQUIRE TESTCASES ~ygrek/lib/testcase.f

TESTCASES FILE-EXIST
(( S" .." FILE-EXIST -> TRUE ))
(( S" extra.f" FILE-EXIST -> TRUE ))
(( S" ?*?" FILE-EXIST -> FALSE ))
END-TESTCASES

TESTCASES FILE-EXISTS
(( S" .." FILE-EXISTS -> FALSE ))
(( S" extra.f" FILE-EXISTS -> TRUE ))
(( S" ?*?" FILE-EXISTS -> FALSE ))
END-TESTCASES
