\ 30.Mar.2004 Tue 23:26

REQUIRE [UNDEFINED]  lib\include\tools.f

[UNDEFINED] INCLUDE-FILE-WITH [IF]
: INCLUDE-FILE-WITH ( i*x fileid xt -- j*x )
  OVER >R  RECEIVE-WITH
  R> CLOSE-FILE SWAP THROW THROW
;
[THEN]

[UNDEFINED] INCLUDED-WITH [IF]
: INCLUDED-WITH ( a u  xt -- )
  >R 
  R/O OPEN-FILE-SHARED THROW
  R> INCLUDE-FILE-WITH
;
[THEN]

