\ 30.Mar.2004 Tue 23:26

REQUIRE [UNDEFINED]  lib\include\tools.f

[UNDEFINED] INCLUDE-FILE-WITH [IF]
: INCLUDE-FILE-WITH ( i*x fileid xt -- j*x )
  OVER >R  RECEIVE-WITH
  R> CLOSE-FILE SWAP THROW THROW
;
[THEN]

[UNDEFINED] INCLUDE-SFILE-WITH [IF]
: INCLUDE-SFILE-WITH ( i*x addr u xt -- j*x )
  CURFILE @ >R  >R 
  2DUP 2>R   R/O OPEN-FILE-SHARED THROW
  2R> HEAP-COPY CURFILE !
  R> ['] INCLUDE-FILE-WITH CATCH
  CURFILE @ FREE DROP
  R> CURFILE !                   THROW
;
[THEN]

[UNDEFINED] INCLUDED-WITH [IF]
: INCLUDED-WITH ( a u  xt -- )
  >R 
  R/O OPEN-FILE-SHARED THROW
  R> INCLUDE-FILE-WITH
;
[THEN]

