




CONCEIVE 
`DUP & EXEC, 
`0= & EXEC, ZBFW, 
`DROP & EXEC, EXIT, RFW 
`DUP & EXEC, 1 LIT, 
`= & EXEC, ZBFW, 
`DROP & EXEC, 
`LIT, & EXEC, EXIT, RFW 
`DUP & EXEC, 2 LIT, 
`= & EXEC, ZBFW, 
`DROP & EXEC, 
`LIT, & EXEC, `LIT, & LIT, 
`EXEC, & EXEC, EXIT, RFW 
`1- & EXEC, 
`SWAP & EXEC, 
`LIT, & EXEC, 
`LIT, & EXEC, GERM LIT, 
`EXEC, & EXEC, 
BIRTH `TS-LIT NAMING- 
CONCEIVE 
`DUP & EXEC, 
`0= & EXEC, ZBFW, 
`DROP & EXEC, 
`EXECUTE & EXEC, EXIT, RFW 
`DUP & EXEC, 1 LIT, 
`= & EXEC, ZBFW, 
`DROP & EXEC, 
`EXEC, & EXEC, EXIT, RFW 
`DUP & EXEC, 2 LIT, 
`= & EXEC, ZBFW, 
`DROP & EXEC, 
`LIT, & EXEC, `EXEC, & LIT, 
`EXEC, & EXEC, EXIT, RFW 
`1- & EXEC, 
`SWAP & EXEC, 
`LIT, & EXEC, 
`LIT, & EXEC, GERM LIT, 
`EXEC, & EXEC, 
BIRTH `TS-EXEC NAMING- 
CONCEIVE 
`DUP & EXEC, 
`0= & EXEC, ZBFW, 
`DROP & EXEC, EXIT, RFW 
`DUP & EXEC, 1 LIT, 
`= & EXEC, ZBFW, 
`DROP & EXEC, 
`SLIT, & EXEC, EXIT, RFW 
`DUP & EXEC, 2 LIT, 
`= & EXEC, ZBFW, 
`DROP & EXEC, 
`SLIT, & EXEC, `SLIT, & LIT, 
`EXEC, & EXEC, EXIT, RFW 
`1- & EXEC, 
`-ROT & EXEC, 
`SLIT, & EXEC, 
`LIT, & EXEC, GERM LIT, 
`EXEC, & EXEC, 
BIRTH `TS-SLIT NAMING- 
CONCEIVE 
`DUP & EXEC, 
`0= & EXEC, ZBFW, 
`DROP & EXEC, EXIT, RFW 
`DUP & EXEC, 1 LIT, 
`= & EXEC, ZBFW, 
`DROP & EXEC, 
`2LIT, & EXEC, EXIT, RFW 
`DUP & EXEC, 2 LIT, 
`= & EXEC, ZBFW, 
`DROP & EXEC, 
`2LIT, & EXEC, `2LIT, & LIT, 
`EXEC, & EXEC, EXIT, RFW 
`1- & EXEC, 
`-ROT & EXEC, 
`2LIT, & EXEC, 
`LIT, & EXEC, GERM LIT, 
`EXEC, & EXEC, 
BIRTH `TS-2LIT NAMING- 

ALIGN HERE 0 , CONCEIVE LIT, BIRTH `STATE NAMING- 


ALIGN HERE 0 , CONCEIVE LIT, BIRTH `M NAMING- 
CONCEIVE 
`M & EXEC, 
`@ & EXEC, ZBFW, 5005 LIT, 
`THROW & EXEC, RFW 
`M & EXEC, 
`1+! & EXEC, 
BIRTH `INC-M NAMING- 
CONCEIVE 
`M & EXEC, 
`@ & EXEC, 
`0= & EXEC, ZBFW, 5004 LIT, 
`THROW & EXEC, RFW 
`M & EXEC, 
`1-! & EXEC, 
BIRTH `DEC-M NAMING- 
CONCEIVE 
`STATE & EXEC, 
`1+! & EXEC, 
BIRTH `INC-S NAMING- 
CONCEIVE 
`STATE & EXEC, 
`@ & EXEC, 
`0= & EXEC, ZBFW, 5004 LIT, 
`THROW & EXEC, RFW 
`STATE & EXEC, 
`1-! & EXEC, 
BIRTH `DEC-S NAMING- 
CONCEIVE 
`M & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-LIT & EXEC, GERM LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, EXIT, RFW RFW 
`STATE & EXEC, 
`@ & EXEC, 
`TS-LIT & EXEC, 
BIRTH `T-LIT NAMING- 
CONCEIVE 
`M & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-LIT & EXEC, GERM LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, EXIT, RFW RFW 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
BIRTH `T-EXEC NAMING- 
CONCEIVE 
`M & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-SLIT & EXEC, GERM LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, EXIT, RFW RFW 
`STATE & EXEC, 
`@ & EXEC, 
`TS-SLIT & EXEC, 
BIRTH `T-SLIT NAMING- 
CONCEIVE 
`M & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-2LIT & EXEC, GERM LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, EXIT, RFW RFW 
`STATE & EXEC, 
`@ & EXEC, 
`TS-2LIT & EXEC, 
BIRTH `T-2LIT NAMING- 
CONCEIVE 
`M & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-LIT & EXEC, GERM LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, EXIT, RFW RFW 

BIRTH `M-LIT NAMING- 
CONCEIVE 
`M & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-LIT & EXEC, GERM LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, EXIT, RFW RFW 
`EXECUTE & EXEC, 
BIRTH `M-EXEC NAMING- 
CONCEIVE 
`DEC-S & LIT, 
`M-EXEC & EXEC, 
BIRTH `M-DEC-STATE NAMING- 
CONCEIVE 
`INC-S & LIT, 
`M-EXEC & EXEC, 
BIRTH `M-INC-STATE NAMING- 




CONCEIVE 
`DUP & EXEC, 1 LIT, 
`Ult & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`2DUP & EXEC, 
`OVER & EXEC, 
`C@ & EXEC, `- DROP C@ LIT, 
`= & EXEC, 
`DUP & EXEC, 
`>R & EXEC, ZBFW, 
`1- & EXEC, 
`SWAP & EXEC, 
`CHAR+ & EXEC, 
`SWAP & EXEC, RFW 0 LIT, 0 LIT, 
`2SWAP & EXEC, 
`>NUMBER & EXEC, 
`NIP & EXEC, ZBFW, 
`RDROP & EXEC, 
`2DROP & EXEC, 
`FALSE & EXEC, EXIT, RFW 
`R> & EXEC, ZBFW, 
`DNEGATE & EXEC, RFW 
`2SWAP & EXEC, 
`2DROP & EXEC, 
`TRUE & EXEC, 
BIRTH `I-DLIT NAMING- 
CONCEIVE 
`I-DLIT & EXEC, ZBFW, 
`D>S & EXEC, 
`TRUE & EXEC, EXIT, RFW 
`FALSE & EXEC, 
BIRTH `I-LIT NAMING- 
CONCEIVE 
`DUP & EXEC, 2 LIT, 
`Ult & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`2DUP & EXEC, 
`1- & EXEC, 
`CHARS & EXEC, 
`+ & EXEC, 
`C@ & EXEC, `. DROP C@ LIT, 
`= & EXEC, ZBFW, 
`1- & EXEC, 
`I-DLIT & EXEC, ZBFW, 
`TRUE & EXEC, EXIT, RFW 
`1+ & EXEC, RFW 
`FALSE & EXEC, 
BIRTH `I-DLIT-FORM NAMING- 
CONCEIVE 
`DUP & EXEC, 3 LIT, 
`Ult & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`OVER & EXEC, 2 LIT, `0x SLIT, 
`CEQUAL & EXEC, 
`0eq & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`OVER & EXEC, 
`CHAR+ & EXEC, 
`CHAR+ & EXEC, 
`OVER & EXEC, 2 LIT, 
`- & EXEC, 
`BASE & EXEC, 
`@ & EXEC, 
`>R & EXEC, 
`HEX & EXEC, 
`I-LIT & EXEC, 
`R> & EXEC, 
`BASE & EXEC, 
`! & EXEC, ZBFW, 
`NIP & EXEC, 
`NIP & EXEC, 
`TRUE & EXEC, EXIT, RFW 
`2DROP & EXEC, 
`FALSE & EXEC, 
BIRTH `I-HLIT-FORM NAMING- 
CONCEIVE 
`DUP & EXEC, 2 LIT, 
`Ult & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`OVER & EXEC, 
`C@ & EXEC, `` DROP C@ LIT, 
`neq & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`1- & EXEC, 
`SWAP & EXEC, 
`CHAR+ & EXEC, 
`SWAP & EXEC, 
`TRUE & EXEC, 
BIRTH `I-SLIT-FORM NAMING- 
CONCEIVE 
`SFIND & EXEC, 
`0neq & EXEC, 
BIRTH `I-NATIVE NAMING- 



CONCEIVE 
`STATE & EXEC, 
`@ & EXEC, 
BIRTH `STATE? NAMING- 
CONCEIVE 
`I-SLIT-FORM & EXEC, ZBFW, 
`T-SLIT & EXEC, EXIT, RFW 
`I-NATIVE & EXEC, ZBFW, 
`T-EXEC & EXEC, EXIT, RFW 
`I-LIT & EXEC, ZBFW, 
`T-LIT & EXEC, EXIT, RFW 
`I-HLIT-FORM & EXEC, ZBFW, 
`T-LIT & EXEC, EXIT, RFW 
`I-DLIT-FORM & EXEC, ZBFW, 
`T-2LIT & EXEC, EXIT, RFW 
`CR & EXEC, 
`TYPE & EXEC, 
`CR & EXEC, -321 LIT, 
`THROW & EXEC, 
BIRTH `T-NAME NAMING- 
CONCEIVE 
MBW 
`FINE-HEAD & EXEC, 
`SPLIT-WHITE-FORCE & EXEC, 
`2gtR & EXEC, 
`DUP & EXEC, ZBFW2, 
`T-NAME & EXEC, 
`2Rgt & EXEC, BBW, RFW 
`2DROP & EXEC, 
`RDROP & EXEC, 
`RDROP & EXEC, 
BIRTH `T-PLAIN NAMING- 



ALIGN HERE 0 , CONCEIVE LIT, BIRTH `a-trans NAMING- 
`FALSE &  a-trans !

 

CONCEIVE `: SLIT, 
`SPLIT- & EXEC, 
`0= & EXEC, ZBFW, 0 LIT, 0 LIT, RFW 
`Namespace-uri-for-prefix & EXEC, 
BIRTH `name-n-uri NAMING- 
CONCEIVE 

`CONCEIVE & EXEC, 
`a-trans & EXEC, 
`@ & EXEC, 
`EXEC, & EXEC, 
`DUP & LIT, `EXEC, & EXEC, 
`ZBFW, & EXEC, 
`EXIT, & EXEC, 
`RFW & EXEC, 
`DROP & LIT, `EXEC, & EXEC, 
`EXEC, & EXEC, 
`BIRTH & EXEC, 
`a-trans & EXEC, 
`! & EXEC, 
BIRTH `advice-rule-after NAMING- 
CONCEIVE 

`CONCEIVE & EXEC, 
`EXEC, & EXEC, 
`DUP & LIT, `EXEC, & EXEC, 
`ZBFW, & EXEC, 
`EXIT, & EXEC, 
`RFW & EXEC, 
`DROP & LIT, `EXEC, & EXEC, 
`a-trans & EXEC, 
`@ & EXEC, 
`EXEC, & EXEC, 
`BIRTH & EXEC, 
`a-trans & EXEC, 
`! & EXEC, 
BIRTH `advice-rule-before NAMING- 
CONCEIVE 
`a-trans & EXEC, 
`@ & EXEC, 
`EXECUTE & EXEC, ZBFW, EXIT, RFW 5321 LIT, 
`THROW & EXEC, 
BIRTH `trans-node-force NAMING- 
CONCEIVE 
`cnode & EXEC, 
`>R & EXEC, 
`FirstChild & EXEC, MBW 
`cnode & EXEC, ZBFW2, 
`trans-node-force & EXEC, 
`NextSibling & EXEC, BBW, RFW 
`R> & EXEC, 
`cnode! & EXEC, 
BIRTH `trans-childs NAMING- 
CONCEIVE 
`cnode & EXEC, 
`>R & EXEC, 
`documentElement & EXEC, 
`cnode! & EXEC, 
`trans-childs & EXEC, 
`R> & EXEC, 
`cnode! & EXEC, 
BIRTH `trans-document NAMING- 



ALIGN HERE 0 , CONCEIVE LIT, BIRTH `_document-storage NAMING- 
ALIGN HERE 0 , CONCEIVE LIT, BIRTH `_document-top NAMING- 
CONCEIVE 
`_document-storage & EXEC, 
`@ & EXEC, 
`DUP & EXEC, ZBFW, EXIT, RFW 
`DROP & EXEC, 256000 LIT, 
`NEW-STORAGE & EXEC, 
`DUP & EXEC, 
`_document-storage & EXEC, 
`! & EXEC, 
BIRTH `document-storage NAMING- 
CONCEIVE 
`DISMOUNT & EXEC, 
`>R & EXEC, 
`document-storage & EXEC, 
`MOUNT & EXEC, 0 LIT, 
`, & EXEC, 
`HERE & EXEC, 
`_document-top & EXEC, 
`BIND-NODE & EXEC, 
`, & EXEC, 
`S", & EXEC, 
`DISMOUNT & EXEC, 
`DROP & EXEC, 
`R> & EXEC, 
`MOUNT & EXEC, 
BIRTH `push-document NAMING- 
CONCEIVE 
`DISMOUNT & EXEC, 
`>R & EXEC, 
`document-storage & EXEC, 
`MOUNT & EXEC, 
`_document-top & EXEC, 
`UNBIND-NODE & EXEC, 
`CELL- & EXEC, 
`HERE & EXEC, 
`- & EXEC, 
`ALLOT & EXEC, 
`DISMOUNT & EXEC, 
`DROP & EXEC, 
`R> & EXEC, 
`MOUNT & EXEC, 
BIRTH `drop-document NAMING- 
CONCEIVE 
`_document-top & EXEC, 
`@ & EXEC, 
`CELL+ & EXEC, 
`COUNT & EXEC, 
BIRTH `document-url NAMING- 
CONCEIVE 
`document-url & EXEC, 
`CUT-PATH & EXEC, 
BIRTH `document-base NAMING- 
CONCEIVE 
`_document-top & EXEC, 
`@ & EXEC, 
`0= & EXEC, ZBFW, EXIT, RFW 
`DISMOUNT & EXEC, 
`>R & EXEC, 
`document-storage & EXEC, 
`MOUNT & EXEC, 
`HERE & EXEC, 
`>R & EXEC, 
`document-base & EXEC, 
`S, & EXEC, 
`S, & EXEC, 
`R> & EXEC, 
`HERE & EXEC, 
`OVER & EXEC, 
`- & EXEC, 0 LIT, 
`, & EXEC, 
`DISMOUNT & EXEC, 
`DROP & EXEC, 
`R> & EXEC, 
`MOUNT & EXEC, 
BIRTH `document-based-url NAMING- 


CONCEIVE 
`document-based-url & EXEC, 
`2DUP & EXEC, 
`DefaultLSParser & EXEC, 
`parseURI & EXEC, 
`DUP & EXEC, 
`0= & EXEC, ZBFW, 5003 LIT, 
`THROW & EXEC, RFW 
`DUP & EXEC, 
`>R & EXEC, 
`push-document & EXEC, 
`R@ & EXEC, 
`trans-document & EXEC, 
`R> & EXEC, 
`DefaultLSParser & EXEC, 
`freeDoc & EXEC, 
`drop-document & EXEC, 
BIRTH `EMBODY NAMING- 



