






CONCEIVE 
`SEARCH & EXEC, 
`NIP & EXEC, 
`NIP & EXEC, 
BIRTH `CONTAINS NAMING- 
CONCEIVE 
`ROT & EXEC, 
`OVER & EXEC, 
`ULT & EXEC, ZBFW, 
`2DROP & EXEC, 
`DROP & EXEC, 
`FALSE & EXEC, EXIT, RFW 
`TUCK & EXEC, 
`EQUAL & EXEC, 
BIRTH `STARTS-WITH NAMING- 
CONCEIVE 
`DUP & EXEC, 
`>R & EXEC, 
`2SWAP & EXEC, 
`DUP & EXEC, 
`R@ & EXEC, 
`ULT & EXEC, ZBFW, 
`2DROP & EXEC, 
`2DROP & EXEC, 
`RDROP & EXEC, 
`FALSE & EXEC, EXIT, RFW 
`R@ & EXEC, 
`- & EXEC, 
`+ & EXEC, 
`R> & EXEC, 
`EQUAL & EXEC, 
BIRTH `ENDS-WITH NAMING- 
CONCEIVE 
`DUP & EXEC, 
`>R & EXEC, 
`SEARCH & EXEC, ZBFW, 
`SWAP & EXEC, 
`R@ & EXEC, 
`+ & EXEC, 
`SWAP & EXEC, 
`R> & EXEC, 
`- & EXEC, EXIT, RFW 
`RDROP & EXEC, 
`DROP & EXEC, 0 LIT, 
BIRTH `SUBSTRING-AFTER NAMING- 
CONCEIVE 3 LIT, 
`PICK & EXEC, 
`>R & EXEC, 
`SEARCH & EXEC, ZBFW, 
`DROP & EXEC, 
`R> & EXEC, 
`TUCK & EXEC, 
`- & EXEC, EXIT, RFW 
`RDROP & EXEC, 
`DROP & EXEC, 0 LIT, 
BIRTH `SUBSTRING-BEFORE NAMING- 
CONCEIVE 3 LIT, 
`PICK & EXEC, 
`>R & EXEC, 
`DUP & EXEC, 
`>R & EXEC, 
`SEARCH & EXEC, ZBFW, 
`OVER & EXEC, 
`R@ & EXEC, 
`+ & EXEC, 
`SWAP & EXEC, 
`R> & EXEC, 
`- & EXEC, 
`ROT & EXEC, 
`R@ & EXEC, 
`- & EXEC, 
`R> & EXEC, 
`SWAP & EXEC, 
`TRUE & EXEC, EXIT, RFW 
`2R> & EXEC, 
`2DROP & EXEC, 
`FALSE & EXEC, 
BIRTH `SPLIT- NAMING- 
CONCEIVE 
`DUP & EXEC, 
`>R & EXEC, 3 LIT, 
`PICK & EXEC, 
`>R & EXEC, 
`SEARCH & EXEC, ZBFW, 
`SWAP & EXEC, 
`R@ & EXEC, 
`OVER & EXEC, 
`R> & EXEC, 
`- & EXEC, 
`2SWAP & EXEC, 
`R@ & EXEC, 
`+ & EXEC, 
`SWAP & EXEC, 
`R> & EXEC, 
`- & EXEC, 
`TRUE & EXEC, EXIT, RFW 
`2R> & EXEC, 
`2DROP & EXEC, 
`FALSE & EXEC, 
BIRTH `SPLIT NAMING- 
CONCEIVE 2 LIT, 
`PICK & EXEC, 
`OVER & EXEC, 
`ULT & EXEC, ZBFW, 
`2DROP & EXEC, 
`FALSE & EXEC, EXIT, RFW 
`DUP & EXEC, 
`>R & EXEC, 3 LIT, 
`PICK & EXEC, 
`R@ & EXEC, 
`EQUAL & EXEC, 
`0EQ & EXEC, ZBFW, 
`RDROP & EXEC, 
`FALSE & EXEC, EXIT, RFW 
`SWAP & EXEC, 
`R@ & EXEC, 
`+ & EXEC, 
`SWAP & EXEC, 
`R> & EXEC, 
`- & EXEC, 
`TRUE & EXEC, 
BIRTH `MATCH-HEAD NAMING- 

CONCEIVE 
`MATCH-HEAD & EXEC, 
BIRTH `MATCH-STARTS NAMING- 

CONCEIVE 
`DUP & EXEC, ZBFW, 
`SWAP & EXEC, 
`CHAR+ & EXEC, 
`SWAP & EXEC, 
`CHAR- & EXEC, EXIT, RFW 

BIRTH `TAIL NAMING- 
CONCEIVE 
`DUP & EXEC, ZBFW, 
`DROP & EXEC, 
`/CHAR & EXEC, EXIT, RFW 

BIRTH `HEAD NAMING- 
CONCEIVE 
`2DUP & EXEC, 
`HEAD & EXEC, 
`2SWAP & EXEC, 
`TAIL & EXEC, 
BIRTH `HEAD|TAIL NAMING- 
CONCEIVE 
`2DUP & EXEC, 
`TAIL & EXEC, 
`2SWAP & EXEC, 
`HEAD & EXEC, 
BIRTH `TAIL|HEAD NAMING- 




CONCEIVE 
`DUP & EXEC, 
`0= & EXEC, ZBFW, 
`DROP & EXEC, EXIT, RFW 
`DUP & EXEC, 1 LIT, 
`= & EXEC, ZBFW, 
`DROP & EXEC, 
`LIT, & EXEC, EXIT, RFW 
`DUP & EXEC, 2 LIT, 
`= & EXEC, ZBFW, 
`DROP & EXEC, 
`LIT, & EXEC, `LIT, & LIT, 
`EXEC, & EXEC, EXIT, RFW 
`1- & EXEC, 
`SWAP & EXEC, 
`LIT, & EXEC, 
`LIT, & EXEC, GERM LIT, 
`EXEC, & EXEC, 
BIRTH `TS-LIT NAMING- 
CONCEIVE 
`DUP & EXEC, 
`0= & EXEC, ZBFW, 
`DROP & EXEC, 
`EXECUTE & EXEC, EXIT, RFW 
`DUP & EXEC, 1 LIT, 
`= & EXEC, ZBFW, 
`DROP & EXEC, 
`EXEC, & EXEC, EXIT, RFW 
`DUP & EXEC, 2 LIT, 
`= & EXEC, ZBFW, 
`DROP & EXEC, 
`LIT, & EXEC, `EXEC, & LIT, 
`EXEC, & EXEC, EXIT, RFW 
`1- & EXEC, 
`SWAP & EXEC, 
`LIT, & EXEC, 
`LIT, & EXEC, GERM LIT, 
`EXEC, & EXEC, 
BIRTH `TS-EXEC NAMING- 
CONCEIVE 
`DUP & EXEC, 
`0= & EXEC, ZBFW, 
`DROP & EXEC, EXIT, RFW 
`DUP & EXEC, 1 LIT, 
`= & EXEC, ZBFW, 
`DROP & EXEC, 
`SLIT, & EXEC, EXIT, RFW 
`DUP & EXEC, 2 LIT, 
`= & EXEC, ZBFW, 
`DROP & EXEC, 
`SLIT, & EXEC, `SLIT, & LIT, 
`EXEC, & EXEC, EXIT, RFW 
`1- & EXEC, 
`-ROT & EXEC, 
`SLIT, & EXEC, 
`LIT, & EXEC, GERM LIT, 
`EXEC, & EXEC, 
BIRTH `TS-SLIT NAMING- 
CONCEIVE 
`DUP & EXEC, 
`0= & EXEC, ZBFW, 
`DROP & EXEC, EXIT, RFW 
`DUP & EXEC, 1 LIT, 
`= & EXEC, ZBFW, 
`DROP & EXEC, 
`2LIT, & EXEC, EXIT, RFW 
`DUP & EXEC, 2 LIT, 
`= & EXEC, ZBFW, 
`DROP & EXEC, 
`2LIT, & EXEC, `2LIT, & LIT, 
`EXEC, & EXEC, EXIT, RFW 
`1- & EXEC, 
`-ROT & EXEC, 
`2LIT, & EXEC, 
`LIT, & EXEC, GERM LIT, 
`EXEC, & EXEC, 
BIRTH `TS-2LIT NAMING- 

SP@ >CS SP@ CS> EQ ?DUP XOR ALIGN HERE SWAP , CONCEIVE LIT, BIRTH `STATE NAMING- 


SP@ >CS SP@ CS> EQ ?DUP XOR ALIGN HERE SWAP , CONCEIVE LIT, BIRTH `M NAMING- 
CONCEIVE 
`M & EXEC, 
`@ & EXEC, ZBFW, -5005 LIT, 
`THROW & EXEC, RFW 
`M & EXEC, 
`1+! & EXEC, 
BIRTH `INC-M NAMING- 
CONCEIVE 
`M & EXEC, 
`@ & EXEC, 
`0= & EXEC, ZBFW, -5004 LIT, 
`THROW & EXEC, RFW 
`M & EXEC, 
`1-! & EXEC, 
BIRTH `DEC-M NAMING- 
CONCEIVE 
`STATE & EXEC, 
`1+! & EXEC, 
BIRTH `INC-S NAMING- 
CONCEIVE 
`STATE & EXEC, 
`@ & EXEC, 
`0= & EXEC, ZBFW, -5004 LIT, 
`THROW & EXEC, RFW 
`STATE & EXEC, 
`1-! & EXEC, 
BIRTH `DEC-S NAMING- 
CONCEIVE 
`M & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-LIT & EXEC, GERM LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, EXIT, RFW RFW 
`STATE & EXEC, 
`@ & EXEC, 
`TS-LIT & EXEC, 
BIRTH `T-LIT NAMING- 
CONCEIVE 
`M & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-LIT & EXEC, GERM LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, EXIT, RFW RFW 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, 
BIRTH `T-EXEC NAMING- 
CONCEIVE 
`M & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-SLIT & EXEC, GERM LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, EXIT, RFW RFW 
`STATE & EXEC, 
`@ & EXEC, 
`TS-SLIT & EXEC, 
BIRTH `T-SLIT NAMING- 
CONCEIVE 
`M & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-2LIT & EXEC, GERM LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, EXIT, RFW RFW 
`STATE & EXEC, 
`@ & EXEC, 
`TS-2LIT & EXEC, 
BIRTH `T-2LIT NAMING- 
CONCEIVE 
`M & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-LIT & EXEC, GERM LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, EXIT, RFW RFW 

BIRTH `M-LIT NAMING- 
CONCEIVE 
`M & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, ZBFW, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-LIT & EXEC, GERM LIT, 
`STATE & EXEC, 
`@ & EXEC, 
`TS-EXEC & EXEC, EXIT, RFW RFW 
`EXECUTE & EXEC, 
BIRTH `M-EXEC NAMING- 
CONCEIVE 
`DEC-S & LIT, 
`M-EXEC & EXEC, 
BIRTH `M-DEC-STATE NAMING- 
CONCEIVE 
`INC-S & LIT, 
`M-EXEC & EXEC, 
BIRTH `M-INC-STATE NAMING- 




CONCEIVE 
`DUP & EXEC, 1 LIT, 
`ULT & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`2DUP & EXEC, 
`OVER & EXEC, 
`C@ & EXEC, `- DROP C@ LIT, 
`= & EXEC, 
`DUP & EXEC, 
`>R & EXEC, ZBFW, 
`1- & EXEC, 
`SWAP & EXEC, 
`CHAR+ & EXEC, 
`SWAP & EXEC, RFW 0 LIT, 0 LIT, 
`2SWAP & EXEC, 
`>NUMBER & EXEC, 
`NIP & EXEC, ZBFW, 
`RDROP & EXEC, 
`2DROP & EXEC, 
`FALSE & EXEC, EXIT, RFW 
`R> & EXEC, ZBFW, 
`DNEGATE & EXEC, RFW 
`2SWAP & EXEC, 
`2DROP & EXEC, 
`TRUE & EXEC, 
BIRTH `I-DLIT NAMING- 
CONCEIVE 
`I-DLIT & EXEC, ZBFW, 
`D>S & EXEC, 
`TRUE & EXEC, EXIT, RFW 
`FALSE & EXEC, 
BIRTH `I-LIT NAMING- 
CONCEIVE 
`DUP & EXEC, 2 LIT, 
`ULT & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`2DUP & EXEC, 
`1- & EXEC, 
`CHARS & EXEC, 
`+ & EXEC, 
`C@ & EXEC, `. DROP C@ LIT, 
`= & EXEC, ZBFW, 
`1- & EXEC, 
`I-DLIT & EXEC, ZBFW, 
`TRUE & EXEC, EXIT, RFW 
`1+ & EXEC, RFW 
`FALSE & EXEC, 
BIRTH `I-DLIT-FORM NAMING- 
CONCEIVE 
`DUP & EXEC, 3 LIT, 
`ULT & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`OVER & EXEC, 2 LIT, `0x SLIT, 
`CEQUAL & EXEC, 
`0EQ & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`OVER & EXEC, 
`CHAR+ & EXEC, 
`CHAR+ & EXEC, 
`OVER & EXEC, 2 LIT, 
`- & EXEC, 
`BASE & EXEC, 
`@ & EXEC, 
`>R & EXEC, 
`HEX & EXEC, 
`I-LIT & EXEC, 
`R> & EXEC, 
`BASE & EXEC, 
`! & EXEC, ZBFW, 
`NIP & EXEC, 
`NIP & EXEC, 
`TRUE & EXEC, EXIT, RFW 
`2DROP & EXEC, 
`FALSE & EXEC, 
BIRTH `I-HLIT-FORM NAMING- 
CONCEIVE 
`DUP & EXEC, 2 LIT, 
`ULT & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`OVER & EXEC, 
`C@ & EXEC, `` DROP C@ LIT, 
`NEQ & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`1- & EXEC, 
`SWAP & EXEC, 
`CHAR+ & EXEC, 
`SWAP & EXEC, 
`TRUE & EXEC, 
BIRTH `I-SLIT-FORM NAMING- 
CONCEIVE 
`SFIND & EXEC, 
`0NEQ & EXEC, 
BIRTH `I-NATIVE NAMING- 



CONCEIVE 
`STATE & EXEC, 
`@ & EXEC, 
BIRTH `STATE? NAMING- 
CONCEIVE 
`STATE & EXEC, 
`@ & EXEC, 
`0EQ & EXEC, 
BIRTH `STATE0? NAMING- 




CONCEIVE 
`SP@ & EXEC, 
`>R & EXEC, 
`EXECUTE & EXEC, 
`SP@ & EXEC, 
`R> & EXEC, 
`EQ & EXEC, 
`0EQ & EXEC, ZBFW, -5010 LIT, 
`THROW & EXEC, RFW 

BIRTH `EXECUTE-BALANCED(+1) NAMING- 
CONCEIVE 
`>R & EXEC, `:: SLIT, 
`SPLIT- & EXEC, 
`0EQ & EXEC, ZBFW, 
`R> & EXEC, 
`SEARCH-WORDLIST & EXEC, EXIT, RFW 
`R> & EXEC, 
`SEARCH-WORDLIST & EXEC, 
`0EQ & EXEC, ZBFW, 
`2DROP & EXEC, 
`FALSE & EXEC, EXIT, RFW 
`EXECUTE-BALANCED(+1) & EXEC, GERM >CS BBW, 

BIRTH `(I-QNATIVE) NAMING- 
CONCEIVE 
`2DUP & EXEC, `:: SLIT, 
`SPLIT- & EXEC, 
`0EQ & EXEC, ZBFW, 
`2DROP & EXEC, 
`FALSE & EXEC, EXIT, RFW 
`I-NATIVE & EXEC, 
`0EQ & EXEC, ZBFW, 
`2DROP & EXEC, 
`2DROP & EXEC, 
`FALSE & EXEC, EXIT, RFW 
`EXECUTE-BALANCED(+1) & EXEC, 
`(I-QNATIVE) & EXEC, 
`0EQ & EXEC, ZBFW, 
`FALSE & EXEC, EXIT, RFW 
`NIP & EXEC, 
`NIP & EXEC, 
`TRUE & EXEC, 
BIRTH `I-QNATIVE NAMING- 

CONCEIVE 
`I-SLIT-FORM & EXEC, ZBFW, 
`T-SLIT & EXEC, EXIT, RFW 
`I-NATIVE & EXEC, ZBFW, 
`T-EXEC & EXEC, EXIT, RFW 
`I-QNATIVE & EXEC, ZBFW, 
`T-EXEC & EXEC, EXIT, RFW 
`I-LIT & EXEC, ZBFW, 
`T-LIT & EXEC, EXIT, RFW 
`I-HLIT-FORM & EXEC, ZBFW, 
`T-LIT & EXEC, EXIT, RFW 
`I-DLIT-FORM & EXEC, ZBFW, 
`T-2LIT & EXEC, EXIT, RFW 
`CR & EXEC, 
`TYPE & EXEC, 
`CR & EXEC, -321 LIT, 
`THROW & EXEC, 
BIRTH `T-NAME NAMING- 
CONCEIVE 
MBW 
`FINE-HEAD & EXEC, 
`SPLIT-WHITE-FORCE & EXEC, 
`2>R & EXEC, 
`DUP & EXEC, ZBFW2, 
`T-NAME & EXEC, 
`2R> & EXEC, BBW, RFW 
`2DROP & EXEC, 
`RDROP & EXEC, 
`RDROP & EXEC, 
BIRTH `T-PLAIN NAMING- 
CONCEIVE 
`I-NATIVE & EXEC, ZBFW, EXIT, RFW 
`I-QNATIVE & EXEC, ZBFW, EXIT, RFW -321 LIT, 
`THROW & EXEC, 
BIRTH `I-NATIVE-FORCE NAMING- 






SP@ >CS SP@ CS> EQ ?DUP XOR ALIGN HERE SWAP , CONCEIVE LIT, BIRTH `chain-current NAMING- 
SP@ >CS SP@ CS> EQ ?DUP XOR ALIGN HERE SWAP , CONCEIVE LIT, BIRTH `chain-context NAMING- 
CONCEIVE 0 LIT, 
`, & EXEC, 
`HERE & EXEC, 
`SWAP & EXEC, 
`, & EXEC, 
`chain-current & EXEC, 
`@ & EXEC, 
`BIND-NODE & EXEC, 
BIRTH `advice-before NAMING- 
CONCEIVE 0 LIT, 
`, & EXEC, 
`HERE & EXEC, 
`SWAP & EXEC, 
`, & EXEC, 
`chain-current & EXEC, 
`@ & EXEC, 
`BIND-NODE-TAIL & EXEC, 
BIRTH `advice-after NAMING- 
CONCEIVE 
`chain-context & EXEC, 
`@ & EXEC, 
`DUP & EXEC, 
`0EQ & EXEC, ZBFW, EXIT, RFW 
`@ & EXEC, MBW 
`DUP & EXEC, ZBFW2, 
`DUP & EXEC, 
`>R & EXEC, 
`@ & EXEC, 
`EXECUTE & EXEC, ZBFW, 
`RDROP & EXEC, 
`TRUE & EXEC, EXIT, RFW 
`R> & EXEC, 
`CELL- & EXEC, 
`@ & EXEC, BBW, RFW 


BIRTH `perform-chain NAMING- 
CONCEIVE 
`perform-chain & EXEC, ZBFW, EXIT, RFW 
`ABORT & EXEC, 
BIRTH `perform-chain-sure NAMING- 

SP@ >CS SP@ CS> EQ ?DUP XOR ALIGN HERE SWAP , CONCEIVE LIT, BIRTH `rules-default NAMING- 

`rules-default & EXECUTE 
`DUP & EXECUTE 
`chain-current & EXECUTE 
`! & EXECUTE 
`chain-context & EXECUTE 
`! & EXECUTE 
CONCEIVE 
`advice-after & EXEC, 
BIRTH `advice-rule-after NAMING- 
CONCEIVE 
`advice-before & EXEC, 
BIRTH `advice-rule-before NAMING- 
CONCEIVE 
`perform-chain & EXEC, ZBFW, EXIT, RFW -5321 LIT, 
`THROW & EXEC, 
BIRTH `trans-node-force NAMING- 
CONCEIVE 
`chain-context & EXEC, 
`@ & EXEC, 
`>R & EXEC, 
`chain-context & EXEC, 
`! & EXEC, 
`trans-node-force & EXEC, 
`R> & EXEC, 
`chain-context & EXEC, 
`! & EXEC, 
BIRTH `apply-rules NAMING- 


`document-context-hidden WORDLIST-NAMED PUSH-DEVELOP 


`dataspace-hidden WORDLIST-NAMED PUSH-DEVELOP 
SP@ >CS SP@ CS> EQ ?DUP XOR ALIGN HERE SWAP , CONCEIVE LIT, BIRTH `D0 NAMING- 
SP@ >CS SP@ CS> EQ ?DUP XOR ALIGN HERE SWAP , CONCEIVE LIT, BIRTH `DP NAMING- 
SP@ >CS SP@ CS> EQ ?DUP XOR ALIGN HERE SWAP , CONCEIVE LIT, BIRTH `D9 NAMING- 
BEGIN-EXPORT 



CONCEIVE 
`DP & EXEC, 
`@ & EXEC, 
BIRTH `HERE NAMING- 
CONCEIVE 
`D9 & EXEC, 
`@ & EXEC, 
`DP & EXEC, 
`@ & EXEC, 
`- & EXEC, 
BIRTH `UNUSED NAMING- 
CONCEIVE 
`DP & EXEC, 
`+! & EXEC, 
BIRTH `ALLOT NAMING- 
CONCEIVE 
`DP & EXEC, 
`@ & EXEC, 
`ALIGNED & EXEC, 
`DP & EXEC, 
`! & EXEC, 
BIRTH `ALIGN NAMING- 

CONCEIVE 
`HERE & EXEC, 
`C! & EXEC, 
`/CHAR & EXEC, 
`ALLOT & EXEC, 
BIRTH `C, NAMING- 
CONCEIVE 
`HERE & EXEC, 
`! & EXEC, 
`/CELL & EXEC, 
`ALLOT & EXEC, 
BIRTH `, NAMING- 
CONCEIVE 
`HERE & EXEC, 
`2! & EXEC, 2 LIT, 
`CELLS & EXEC, 
`ALLOT & EXEC, 
BIRTH `2, NAMING- 
CONCEIVE 
`UNUSED & EXEC, 
`UMIN & EXEC, 
`HERE & EXEC, 
`SWAP & EXEC, 
`DUP & EXEC, 
`ALLOT & EXEC, 
`MOVE & EXEC, 
BIRTH `S, NAMING- 
CONCEIVE 
`DUP & EXEC, 
`, & EXEC, 
`S, & EXEC, 0 LIT, 
`C, & EXEC, 
BIRTH `SXZ, NAMING- 
CONCEIVE 
`DUP & EXEC, 
`C, & EXEC, 
`S, & EXEC, 0 LIT, 
`C, & EXEC, 
BIRTH `SCZ, NAMING- 
CONCEIVE 
`DP & EXEC, 
`@ & EXEC, 
`D0 & EXEC, 
`@ & EXEC, 
`D9 & EXEC, 
`@ & EXEC, 3 LIT, 
BIRTH `SAVE-DATASPACE NAMING- 
CONCEIVE 3 LIT, 
`NEQ & EXEC, ZBFW, 
`ABORT & EXEC, RFW 
`D9 & EXEC, 
`! & EXEC, 
`D0 & EXEC, 
`! & EXEC, 
`DP & EXEC, 
`! & EXEC, 
BIRTH `RESTORE-DATASPACE NAMING- 
CONCEIVE 
`OVER & EXEC, 
`DUP & EXEC, 
`D0 & EXEC, 
`! & EXEC, 
`DP & EXEC, 
`! & EXEC, 
`+ & EXEC, 
`D9 & EXEC, 
`! & EXEC, 
BIRTH `DATASPACE! NAMING- 
CONCEIVE 
`D0 & EXEC, 
`@ & EXEC, 
`D9 & EXEC, 
`@ & EXEC, 
`OVER & EXEC, 
`- & EXEC, 
BIRTH `DATASPACE NAMING- 
CONCEIVE 
`D0 & EXEC, 
`@ & EXEC, 
`DP & EXEC, 
`@ & EXEC, 
`OVER & EXEC, 
`- & EXEC, 
BIRTH `DATASPACE-CONTENT NAMING- 
CONCEIVE 
`D0 & EXEC, 
`@ & EXEC, 
`DP & EXEC, 
`! & EXEC, 
BIRTH `RESET-DATASPACE NAMING- 

END-EXPORT 
DROP-DEVELOP 


CONCEIVE 
`DUP & EXEC, 
`@ & EXEC, 
`, & EXEC, 
`HERE & EXEC, 
`SWAP & EXEC, 
`! & EXEC, 
BIRTH `PUSH-MARKER NAMING- 
CONCEIVE 
`DUP & EXEC, 
`@ & EXEC, 
`CELL- & EXEC, 
`DUP & EXEC, 
`@ & EXEC, 
`ROT & EXEC, 
`! & EXEC, 
`HERE & EXEC, 
`- & EXEC, 
`ALLOT & EXEC, 
BIRTH `DROP-MARKER NAMING- 

SP@ >CS SP@ CS> EQ ?DUP XOR ALIGN HERE SWAP , CONCEIVE LIT, BIRTH `_doc NAMING- 
SP@ >CS SP@ CS> EQ ?DUP XOR ALIGN HERE SWAP , CONCEIVE LIT, BIRTH `_doc-url NAMING- 
BEGIN-EXPORT 
CONCEIVE 256000 LIT, 
`ALLOCATED & EXEC, 
`DATASPACE! & EXEC, 
`HERE & EXEC, 
`_doc-url & EXEC, 
`! & EXEC, 0 LIT, 
`, & EXEC, 
`_doc & EXEC, 
`0! & EXEC, 
BIRTH `init-document-context NAMING- 
CONCEIVE 
`_doc & EXEC, 
`PUSH-MARKER & EXEC, 
`, & EXEC, 
`_doc-url & EXEC, 
`PUSH-MARKER & EXEC, 
`SCZ, & EXEC, 
BIRTH `push-document NAMING- 
CONCEIVE 
`_doc-url & EXEC, 
`DROP-MARKER & EXEC, 
`_doc & EXEC, 
`DROP-MARKER & EXEC, 
BIRTH `drop-document NAMING- 
CONCEIVE 
`_doc-url & EXEC, 
`@ & EXEC, 
`COUNT & EXEC, 
BIRTH `document-url NAMING- 
CONCEIVE 
`document-url & EXEC, 
`CUT-PATH & EXEC, 
BIRTH `document-base NAMING- 
CONCEIVE 
`HERE & EXEC, 
`>R & EXEC, 
`S, & EXEC, 
`S, & EXEC, 
`R> & EXEC, 
`HERE & EXEC, 
`OVER & EXEC, 
`- & EXEC, 0 LIT, 
`, & EXEC, 
BIRTH `concat-in-document- NAMING- 
CONCEIVE 
`_doc-url & EXEC, 
`@ & EXEC, 
`0EQ & EXEC, ZBFW, EXIT, RFW 
`document-base & EXEC, 
`concat-in-document- & EXEC, 
BIRTH `document-based-url NAMING- 
CONCEIVE 
`_doc-url & EXEC, 
`@ & EXEC, 
`0EQ & EXEC, ZBFW, EXIT, RFW 
`BaseURI & EXEC, 
`concat-in-document- & EXEC, 
BIRTH `cnode-based-url NAMING- 
END-EXPORT 
DROP-DEVELOP 



CONCEIVE `: SLIT, 
`SPLIT- & EXEC, 
`0= & EXEC, ZBFW, 
`2DUP & EXEC, `# SLIT, 
`STARTS-WITH & EXEC, ZBFW, 0 LIT, 0 LIT, EXIT, RFW 0 LIT, 0 LIT, RFW 
`Namespace-uri-for-prefix & EXEC, 
BIRTH `name-n-uri NAMING- 
CONCEIVE 
`cnode & EXEC, 
`>R & EXEC, 
`FirstChild & EXEC, MBW 
`cnode & EXEC, ZBFW2, 
`trans-node-force & EXEC, 
`NextSibling & EXEC, BBW, RFW 
`R> & EXEC, 
`cnode! & EXEC, 
BIRTH `trans-childs NAMING- 
CONCEIVE 
`cnode & EXEC, 
`>R & EXEC, 
`documentElement & EXEC, 
`cnode! & EXEC, 
`trans-childs & EXEC, 
`R> & EXEC, 
`cnode! & EXEC, 
BIRTH `trans-document NAMING- 
CONCEIVE 
`2DUP & EXEC, 
`DefaultLSParser & EXEC, 
`parseURI & EXEC, 
`DUP & EXEC, 
`0= & EXEC, ZBFW, -5003 LIT, 
`THROW & EXEC, RFW 
`DUP & EXEC, 
`>R & EXEC, 
`push-document & EXEC, 
`R@ & EXEC, 
`trans-document & EXEC, 
`R> & EXEC, 
`DefaultLSParser & EXEC, 
`freeDoc & EXEC, 
`drop-document & EXEC, 
BIRTH `EMBODY NAMING- 
CONCEIVE 
`2DUP & EXEC, `/ SLIT, 
`SPLIT- & EXEC, ZBFW, `: SLIT, 
`SUBSTRING-BEFORE & EXEC, 
`NIP & EXEC, ZBFW, 
`2DROP & EXEC, 
`EMBODY & EXEC, 
EXIT, 
RFW RFW 
`2DROP & EXEC, 
`cnode-based-url & EXEC, 
`EMBODY & EXEC, 
BIRTH `Embody NAMING- 



