Document: spforth
Title: Debian spforth Manual
Author: <insert document author here>
Abstract: This manual describes what spforth is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/spforth/spforth.sgml.gz

Format: postscript
Files: /usr/share/doc/spforth/spforth.ps.gz

Format: text
Files: /usr/share/doc/spforth/spforth.text.gz

Format: HTML
Index: /usr/share/doc/spforth/html/index.html
Files: /usr/share/doc/spforth/html/*.html


