\ —ервисы дл€ WinNT

WINAPI: StartServiceCtrlDispatcherA ADVAPI32.DLL
WINAPI: CreateServiceA              ADVAPI32.DLL
WINAPI: OpenSCManagerA              ADVAPI32.DLL
WINAPI: RegisterServiceCtrlHandlerA ADVAPI32.DLL
WINAPI: SetServiceStatus            ADVAPI32.DLL
WINAPI: OpenServiceA                ADVAPI32.DLL
WINAPI: DeleteService               ADVAPI32.DLL
WINAPI: CloseServiceHandle          ADVAPI32.DLL

0    \ структура состо€ни€ сервиса
4 -- dwServiceType
4 -- dwCurrentState
4 -- dwControlsAccepted
4 -- dwWin32ExitCode
4 -- dwServiceSpecificExitCode
4 -- dwCheckPoint
4 -- dwWaitHint
CONSTANT /SERVICE_STATUS

HEX 1FF CONSTANT SERVICE_ALL_ACCESS
     3F CONSTANT SC_MANAGER_ALL_ACCESS
     10 CONSTANT SERVICE_WIN32_OWN_PROCESS

     30 CONSTANT SERVICE_WIN32
    100 CONSTANT SERVICE_INTERACTIVE_PROCESS

      1 CONSTANT SERVICE_ACCEPT_STOP
      2 CONSTANT SERVICE_ACCEPT_PAUSE_CONTINUE
      4 CONSTANT SERVICE_ACCEPT_SHUTDOWN

      1 CONSTANT SERVICE_CONTROL_STOP
      4 CONSTANT SERVICE_CONTROL_INTERROGATE

      1 CONSTANT SERVICE_STOPPED

      1 CONSTANT SERVICE_ERROR_NORMAL
      3 CONSTANT SERVICE_DEMAND_START
      2 CONSTANT S_AUTO
      4 CONSTANT SERVICE_RUNNING
  10000 CONSTANT DELETE_SERVICE
DECIMAL

CREATE SERVICE_STATUS /SERVICE_STATUS ALLOT
SERVICE_STATUS /SERVICE_STATUS ERASE

