
: DEFER VECT ;
: IS POSTPONE TO ; IMMEDIATE

: M+ SWAP >R + R> OVER 0= IF 1+ THEN ;

: ?PAIRS <> ABORT" unpaired" ;

MODULE: $HEX \ translating hex literals from $12AB,CDEF

: BOUNDS OVER + SWAP ;

: hex? ( c -- ? )
  DUP [CHAR] 0 [CHAR] 9 1+ WITHIN 
  SWAP [CHAR] A [CHAR] F 1+ WITHIN 
  OR ;

: $HEX? ( a u -- ? ) 
   DUP 10 <> IF 2DROP FALSE EXIT THEN
   OVER 0 + C@ [CHAR] $ <> IF 2DROP FALSE EXIT THEN
   OVER 1 + 4 BOUNDS DO I C@ hex? 0= IF UNLOOP 2DROP FALSE EXIT THEN LOOP
   OVER 5 + C@ [CHAR] , <> IF ." DDS" 2DROP FALSE EXIT THEN
   OVER 6 + 4 BOUNDS DO I C@ hex? 0= IF UNLOOP 2DROP FALSE EXIT THEN LOOP
   2DROP TRUE ;

EXPORT

: DO-$HEX ( a u -- )
   DROP
   S" 0x0" PAD SWAP CMOVE
   DUP 1 + 4 PAD 3 + SWAP CMOVE
   DUP 6 + 4 PAD 7 + SWAP CMOVE
   DROP
   PAD 11 ?SLITERAL ;

WARNING @   
WARNING 0!
: NOTFOUND
  2DUP 
  $HEX? IF DO-$HEX EXIT THEN
  NOTFOUND ;
WARNING !

;MODULE

\EOF

: ? <> IF ABORT" test failed" THEN ;

ALSO $HEX

S" $1234,ABEF" $HEX?  TRUE ?
S" #1234,5678" $HEX? FALSE ?
S" $123,45678" $HEX? FALSE ?
S" $1234,567"  $HEX? FALSE ?
S" $12G4,5678" $HEX? FALSE ?
