REQUIRE P: ~micro/lib/predicat.f

: ?SLITERAL-ANS94
  0 0 2SWAP
  OVER C@ [CHAR] - = IF 1- SWAP 1+ SWAP TRUE ELSE FALSE THEN >R
  >NUMBER
  DUP 1 > IF 2DROP 2DROP RDROP 0 EXIT THEN
  IF C@ [CHAR] . <> IF 2DROP RDROP 0 EXIT THEN
       R> IF DNEGATE THEN
       [COMPILE] 2LITERAL
  ELSE DROP D>S
       R> IF NEGATE THEN
       [COMPILE] LITERAL
  THEN
  -1
;

: ?SLITERAL-0xHEX
  2DUP
  2 MIN S" 0x" COMPARE
  IF
    2DROP 0
  ELSE
    BASE @ >R
    HEX
    SWAP 2+ SWAP 2-
    ?SLITERAL-ANS94
    R> BASE !
  THEN
;

: ?SLITERAL-AUTOINCLUDE
  OVER C@ [CHAR] " = IF
    2- SWAP 1+ SWAP
  THEN
  2DUP + 0 SWAP C!
  ['] INCLUDED CATCH
  DUP 2 = OVER 3 = OR
  IF 2DROP DROP 0 EXIT
  ELSE THROW THEN
  -1
;

5 2 P: ?SLITERAL-P1 ?SLITERAL-ANS94 ?SLITERAL-0xHEX ?SLITERAL-AUTOINCLUDE ;

VECT <?SLITERAL>
' ?SLITERAL-P1 TO <?SLITERAL>

: ?SLITERAL1
  <?SLITERAL>
  0= ABORT" ç• ãàíÖêÄã"
;

' ?SLITERAL1 TO ?SLITERAL
