\ Управление встроенным браузером. Примеры см. в ~ac/lib/win/window/browser.f

REQUIRE CLSID,  ~ac/lib/win/com/com.f

\ http://source.winehq.org/source/include/mshtml.idl :)

IID_IDispatch
Interface: IID_IHTMLDocument3 {3050f485-98b5-11cf-bb82-00aa00bdce0b}
  Method: ::releaseCapture ( )
  Method: ::recalc ( [defaultvalue, in] VARIANT_BOOL fForce)
  Method: ::createTextNode (        [in] BSTR text,        [retval, out] IHTMLDOMNode **newTextNode)
  Method: ::documentElement ( [retval, out] IHTMLElement **p)
  Method: ::uniqueID ( [retval, out] BSTR *p)
  Method: ::attachEvent (        [in] BSTR event,        [in] IDispatch* pDisp,        [retval, out] VARIANT_BOOL *pfResult)
  Method: ::detachEvent (        [in] BSTR event,        [in] IDispatch *pDisp)
  Method: ::put_onrowsdelete ( [in] VARIANT v)
  Method: ::get_onrowsdelete ( [retval, out] VARIANT *p)
  Method: ::put_onrowsinserted ( [in] VARIANT v)
  Method: ::get_onrowsinserted ( [retval, out] VARIANT *p)
  Method: ::put_oncellchange ( [in] VARIANT v)
  Method: ::get_oncellchange ( [retval, out] VARIANT *p)
  Method: ::put_ondatasetchanged ( [in] VARIANT v)
  Method: ::get_ondatasetchanged ( [retval, out] VARIANT *p)
  Method: ::put_ondataavailable ( [in] VARIANT v)
  Method: ::get_ondataavailable ( [retval, out] VARIANT * p)
  Method: ::put_ondatasetcomplete ( [in] VARIANT v)
  Method: ::get_ondatasetcomplete ( [retval, out] VARIANT *p)
  Method: ::put_onpropertychange ( [in] VARIANT v)
  Method: ::get_onpropertychange ( [retval, out] VARIANT *p)
  Method: ::put_dir ( [in] BSTR v)
  Method: ::get_dir ( [retval, out] BSTR *p)
  Method: ::put_oncontextmenu ( [in] VARIANT v)
  Method: ::het_oncontextmenu ( [retval, out] VARIANT *p)
  Method: ::put_onstop ( [in] VARIANT v)
  Method: ::get_onstop ( [retval, out] VARIANT *p)
  Method: ::createDocumentFragment ( [retval, out] IHTMLDocument2 **pNewDoc)
  Method: ::get_parentDocument ( [retval, out] IHTMLDocument2 **p)
  Method: ::put_enableDownload ( [in] VARIANT_BOOL v)
  Method: ::get_enableDownload ( [retval, out] VARIANT_BOOL *p)
  Method: ::put_baseUrl ( [in] BSTR v)
  Method: ::get_baseUrl ( [retval, out] BSTR *p)
  Method: ::get_childNodes ( [retval, out] IDispatch **p)
  Method: ::put_inheritStyleSheets ( [in] VARIANT_BOOL v)
  Method: ::get_inheritStyleSheets ( [retval, out] VARIANT_BOOL *p)
  Method: ::put_onbeforeeditfocus ( [in] VARIANT v)
  Method: ::get_onbeforeeditfocus ( [retval, out] VARIANT *p)
  Method: ::getElementsByName (        [in] BSTR v,        [retval, out] IHTMLElementCollection **pelColl)
  Method: ::getElementById (        [in] BSTR v,        [retval, out] IHTMLElement **pel)
  Method: ::getElementsByTagName (        [in] BSTR v,        [retval, out] IHTMLElementCollection **pelColl)
Interface;

\ IID_IDispatch
\ Interface: IID_DispHTMLDocument {3050f55f-98b5-11cf-bb82-00aa00bdce0b}
\ то же в другой обертке...
\ Interface;

\ MinGW\include\mshtml.h 

IID_IDispatch
Interface: IID_IHTMLDocument2 {332C4425-26CB-11D0-B483-00C04FD90119}
  Method: ::get_Script ( THIS_ IDispatch**)

  Method: ::get_all ( THIS_ LPHTMLELEMENTCOLLECTION*)
  Method: ::get_body ( THIS_ LPHTMLELEMENT*)
  Method: ::get_activeElement ( THIS_ LPHTMLELEMENT*)
  Method: ::get_images ( THIS_ LPHTMLELEMENTCOLLECTION*)
  Method: ::get_applets ( THIS_ LPHTMLELEMENTCOLLECTION*)
  Method: ::get_links ( THIS_ LPHTMLELEMENTCOLLECTION*)
  Method: ::get_forms ( THIS_ LPHTMLELEMENTCOLLECTION*)
  Method: ::get_anchors ( THIS_ LPHTMLELEMENTCOLLECTION*)
  Method: ::put_title ( THIS_ BSTR)
  Method: ::get_title ( THIS_ BSTR*)
  Method: ::get_scripts ( THIS_ LPHTMLELEMENTCOLLECTION*)
  Method: ::put_designMode ( THIS_ BSTR)
  Method: ::get_designMode ( THIS_ BSTR*)
  Method: ::get_selection ( THIS_ LPHTMLSELECTIONOBJECT*)
  Method: ::get_readyState ( THIS_ BSTR*)
  Method: ::get_frames ( THIS_ LPHTMLFRAMESCOLLECTION*)
  Method: ::get_embeds ( THIS_ LPHTMLELEMENTCOLLECTION*)
  Method: ::get_plugins ( THIS_ LPHTMLELEMENTCOLLECTION*)
  Method: ::put_alinkColor ( THIS_ VARIANT)
  Method: ::get_alinkColor ( THIS_ VARIANT*)
  Method: ::put_bgColor ( THIS_ VARIANT)
  Method: ::get_bgColor ( THIS_ VARIANT*)
  Method: ::put_fgColor ( THIS_ VARIANT)
  Method: ::get_fgColor ( THIS_ VARIANT*)
  Method: ::put_linkColor ( THIS_ VARIANT)
  Method: ::get_linkColor ( THIS_ VARIANT*)
  Method: ::put_vlinkColor ( THIS_ VARIANT)
  Method: ::get_vlinkColor ( THIS_ VARIANT*)
  Method: ::get_referrer ( THIS_ BSTR*)
  Method: ::get_location ( THIS_ LPHTMLLOCATION*)
  Method: ::get_lastModified ( THIS_ BSTR*)
  Method: ::put_URL ( THIS_ BSTR)
  Method: ::get_URL ( THIS_ BSTR*)
  Method: ::put_domain ( THIS_ BSTR)
  Method: ::get_domain ( THIS_ BSTR*)
  Method: ::put_cookie ( THIS_ BSTR)
  Method: ::get_cookie ( THIS_ BSTR*)
  Method: ::put_expands ( THIS_ VARIANT_BOOL)
  Method: ::get_expands ( THIS_ VARIANT_BOOL*)
  Method: ::put_charset ( THIS_ BSTR)
  Method: ::get_charset ( THIS_ BSTR*)
  Method: ::put_defaultCharset ( THIS_ BSTR)
  Method: ::get_defaultCharset ( THIS_ BSTR*)
  Method: ::get_mimeType ( THIS_ BSTR*)
  Method: ::get_fileSize ( THIS_ BSTR*)
  Method: ::get_fileCreatedDate ( THIS_ BSTR*)
  Method: ::get_fileModifiedDate ( THIS_ BSTR*)
  Method: ::get_fileUpdatedDate ( THIS_ BSTR*)
  Method: ::get_security ( THIS_ BSTR*)
  Method: ::get_protocol ( THIS_ BSTR*)
  Method: ::get_nameProp ( THIS_ BSTR*)
  Method: ::write ( THIS_ SAFEARRAY*)
  Method: ::writeln ( THIS_ SAFEARRAY*)
  Method: ::open ( THIS_ BSTR,VARIANT,VARIANT,VARIANT,IDispatch**)
  Method: ::close ( THIS)
  Method: ::clear ( THIS)
  Method: ::queryCommandSupported ( THIS_ BSTR,VARIANT_BOOL*)
  Method: ::queryCommandEnabled ( THIS_ BSTR,VARIANT_BOOL*)
  Method: ::queryCommandState ( THIS_ BSTR,VARIANT_BOOL*)
  Method: ::queryCommandIndeterm ( THIS_ BSTR,VARIANT_BOOL*)
  Method: ::queryCommandText ( THIS_ BSTR,BSTR*)
  Method: ::queryCommandValue ( THIS_ BSTR,VARIANT*)
  Method: ::execCommand ( THIS_ BSTR,VARIANT_BOOL,VARIANT,VARIANT_BOOL*)
  Method: ::execCommandShowHelp ( THIS_ BSTR,VARIANT_BOOL*)
  Method: ::createElement ( THIS_ BSTR,LPHTMLELEMENT*)
  Method: ::put_onhelp ( THIS_ VARIANT)
  Method: ::get_onhelp ( THIS_ VARIANT*)
  Method: ::put_onclick ( THIS_ VARIANT)
  Method: ::get_onclick ( THIS_ VARIANT*)
  Method: ::put_ondblclick ( THIS_ VARIANT)
  Method: ::get_ondblclick ( THIS_ VARIANT*)
  Method: ::put_onkeyup ( THIS_ VARIANT)
  Method: ::get_onkeyup ( THIS_ VARIANT*)
  Method: ::put_onkeydown ( THIS_ VARIANT)
  Method: ::get_onkeydown ( THIS_ VARIANT*)
  Method: ::put_onkeypress ( THIS_ VARIANT)
  Method: ::get_onkeypress ( THIS_ VARIANT*)
  Method: ::put_onmouseup ( THIS_ VARIANT)
  Method: ::get_onmouseup ( THIS_ VARIANT*)
  Method: ::put_onmousedown ( THIS_ VARIANT)
  Method: ::get_onmousedown ( THIS_ VARIANT*)
  Method: ::put_onmousemove ( THIS_ VARIANT)
  Method: ::get_onmousemove ( THIS_ VARIANT*)
  Method: ::put_onmouseout ( THIS_ VARIANT)
  Method: ::get_onmouseout ( THIS_ VARIANT*)
  Method: ::put_onmouseover ( THIS_ VARIANT)
  Method: ::get_onmouseover ( THIS_ VARIANT*)
  Method: ::put_onreadystatechange ( THIS_ VARIANT)
  Method: ::get_onreadystatechange ( THIS_ VARIANT*)
  Method: ::put_onafterupdate ( THIS_ VARIANT)
  Method: ::get_onafterupdate ( THIS_ VARIANT*)
  Method: ::put_onrowexit ( THIS_ VARIANT)
  Method: ::get_onrowexit ( THIS_ VARIANT*)
  Method: ::put_onrowenter ( THIS_ VARIANT)
  Method: ::get_onrowenter ( THIS_ VARIANT*)
  Method: ::put_ondragstart ( THIS_ VARIANT)
  Method: ::get_ondragstart ( THIS_ VARIANT*)
  Method: ::put_onselectstart ( THIS_ VARIANT)
  Method: ::get_onselectstart ( THIS_ VARIANT*)
  Method: ::elementFromPoint ( THIS_ long,long,LPHTMLELEMENT*)
  Method: ::get_parentWindow ( THIS_ LPHTMLWINDOW2*)
  Method: ::get_styleSheets ( THIS_ LPHTMLSTYLESHEETSCOLLECTION*)
  Method: ::put_onbeforeupdate ( THIS_ VARIANT)
  Method: ::get_onbeforeupdate ( THIS_ VARIANT*)
  Method: ::put_onerrorupdate ( THIS_ VARIANT)
  Method: ::get_onerrorupdate ( THIS_ VARIANT*)
  Method: ::toString ( THIS_ BSTR*)
  Method: ::createStyleSheet ( THIS_ BSTR,long,LPHTMLSTYLESHEET*)
Interface;
