#!/bin/bash

# $Id$

rm spf4.o
make -C posix # generate posix/config.auto.f
cd ..
echo Wait a bit while compiling...
./spf4orig src/spf.f
cd src
gcc -o spf4 spf4.o -Wl,forth.ld -ldl -lpthread -v
#cc spf4.o -ldl -lpthread -D_REENTRANT -Xlinker -Tdefault.ld -Xlinker -Tforth.ld -v
mv spf4 ..
