#!/bin/sh
#
# $Id$
#
# Compile SP-Forth for linux
# The default options can be overridden in ./compile.ini

cd ${0%/*} # go to the itself file location
rm spf4.o
make -C posix # generate posix/config.auto.f
cd ..
echo Wait a bit while compiling...
./spf4orig src/spf.f
cd src
gcc -v 2>&1 | grep -F --silent -- '--enable-default-pie' && gcc_nopie="-no-pie"
gcc -o spf4 spf4.o -Wl,forth.ld -ldl -lpthread -v -m32 -fno-pie $gcc_nopie
mv spf4 ..
