#!/bin/bash

# Создание форт-системы из объектного файла
# Ю. Жиловец, 9.06.2007

# Аргументы: рабочий-каталог выходной-файл

if [ $# -lt 2 ]; then
  echo "This file is invoked by SPF when saving a new forth-system"
  exit
fi

DIR=$1
OUT=$2

cc -v $OUT.o -ldl -lpthread -D_REENTRANT -Xlinker -T$DIR/default.ld -Xlinker -T$OUT.ld -o $OUT
